### ISSUE TITLE
Error in refact_fast algorithm

### ISSUE THREAD

**Issue by MartinKahabka** [MartinKahabka/ClIntKahabka#64]
Error in refact_fast algorithm, file variantPromoterRegion_refact.py

Error:
Traceback (most recent call last):
  File "/nfs/geo/itg/kahabka/ClIntKahabka/promoter/variantPromoterRegion_refact.py", line 275, in <module>
    fastAnalyis_refac(input_file, filtered_vcf_file, promoter_sum_file, promoter, start_prom, end_prom)
  File "/nfs/geo/itg/kahabka/ClIntKahabka/promoter/variantPromoterRegion_refact.py", line 153, in fastAnalyis_refac
    line = input_file.getLine(index)
  File "/nfs/geo/itg/kahabka/ClIntKahabka/promoter/variantPromoterRegion_refact.py", line 36, in getLine
    while self.file.read(1) != "\n" and start_offset < byte:
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbc in position 0: invalid start byte

**Comment by MartinKahabka** [comment]
error can be fixed by using 
open(..., errors = 'ignore')
